Create tracking microservice for Artemis
ls1intum/Athene pull request #17
Opened 2020-06-17 17:16 UTC by JonasPetry

TODO

2020-06-24 20:46 UTC, jpbernius commented on .github/workflows/dockerimage.yml
> +    - name: Build and Push the artemis-tracking Docker image
```suggestion
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: github.ref == 'refs/heads/master'
    - name: Build and Push the artemis-tracking Docker image
```

2020-07-09 12:56 UTC, jpbernius commented on tracking/src/main.py
> +        if (encoded_jwt_token.get('result_id')) != feedback.get('participation').get('results')[0].get('id'):
```suggestion
        if encoded_jwt_token.get('result_id') != feedback.get('participation').get('results')[0].get('id'):
```

2020-07-09 12:57 UTC, jpbernius commented on tracking/src/main.py
> +
```suggestion
```

2020-07-14 07:47 UTC, jpbernius submitted a review, later dismissed

2020-07-25 11:11 UTC, linusmichel requested changes
Looks good to me and works in my environment

2020-07-25 11:11 UTC, linusmichel commented on init-mongo.js
> +);
Newline at EOF missing

2020-07-25 11:11 UTC, linusmichel commented on docker-compose.yml
> +
We need to add this to the traefik config once the load-balancer branch is merged as well

2020-07-25 11:11 UTC, linusmichel commented on tracking/Dockerfile
> +CMD uvicorn --port 80 --host 0.0.0.0 src.main:app
Newline at EOF missing

2020-07-28 08:33 UTC, linusmichel approved these changes

2020-09-24 12:35 UTC, merged