Similarity component siamese network
ls1intum/Athene pull request #25
Opened 2020-07-13 15:20 UTC by clemenszuck

**Description**
Adds a new similarity component including two new API-routes:

* http://localhost:8003/similarity to calculate a similarity matrix for a list of embeddings

* http://localhost:8003/train to re-train the network on a list of labeled embedding pairs

**Testing**
* Start up Athene using `docker-compose up -d`
* Test if the API routes work as expected (example JSONs and expected results in [similarity/README.md](https://github.com/ls1intum/Athene/blob/similarity-component-siamese-network/similarity/README.md))

2020-07-27 08:34 UTC, linusmichel requested changes
Functionality works as expected! 👍 
Added some minor formatting comments.

2020-07-27 08:34 UTC, linusmichel commented on similarity/src/SimilarityResource.py
> +        self.__logger.debug("-" * 80)
Newline at EOF missing

2020-07-27 08:34 UTC, linusmichel commented on similarity/src/entities.py
> +        return cls(dict['embedding1'], dict['embedding2'], dict['label'])
Newline at EOF missing

2020-07-27 08:34 UTC, linusmichel commented on similarity/src/errors.py
> +requireEmbeddingPairs = HTTPBadRequest("No embedding pairs provided.", "Must provide embedding pairs to train network.")
Newline at EOF missing

2020-07-27 08:34 UTC, linusmichel commented on similarity/src/resources/siamese-model-default.json
> +{"class_name": "Model", "config": {"name": "model_1", "layers": [{"name": "input_1", "class_name": "InputLayer", "config": {"batch_input_shape": [null, 1024, 1], "dtype": "float32", "sparse": false,
Newline at EOF missing

2020-07-28 08:31 UTC, JonasPetry reviewed
Functionality works for me, good job!

2020-08-03 13:27 UTC, clemenszuck commented on .github/workflows/dockerimage.yml
> +      run: ./.github/workflows/scripts/dockerimage.sh "similarity"
Fixed

2020-08-03 13:27 UTC, clemenszuck commented on similarity/Dockerfile
> +CMD gunicorn -b 0.0.0.0:8000 src.app
Fixed

2020-08-03 13:27 UTC, clemenszuck commented on similarity/requirements.txt
> +
Fixed

2020-08-03 13:27 UTC, clemenszuck commented on similarity/requirements.txt
> +# Listed dependencies as of 2020-06-24
Fixed

2020-08-03 13:27 UTC, clemenszuck commented on similarity/src/NetworkTrainingResource.py
> +        self.__siameseNetwork.build_siamese_model((1024, 1))
Good point, it definitely could be useful! I changed it.

2020-08-03 13:27 UTC, clemenszuck commented on similarity/src/SimilarityResource.py
> +        self.__logger.debug("-" * 80)
Fixed

2020-08-03 13:27 UTC, clemenszuck commented on similarity/src/entities.py
> +        return cls(dict['embedding1'], dict['embedding2'], dict['label'])
Fixed

2020-08-03 13:28 UTC, clemenszuck commented on similarity/src/errors.py
> +requireEmbeddingPairs = HTTPBadRequest("No embedding pairs provided.", "Must provide embedding pairs to train network.")
Fixed

2020-08-03 13:28 UTC, clemenszuck commented on similarity/src/resources/siamese-model-default.json
> +{"class_name": "Model", "config": {"name": "model_1", "layers": [{"name": "input_1", "class_name": "InputLayer", "config": {"batch_input_shape": [null, 1024, 1], "dtype": "float32", "sparse": false,
Fixed

2020-08-13 09:12 UTC, JonasPetry approved these changes
Re-Approve

2023-05-25 21:02 UTC, closed without merging