Feature/merge clusters
ls1intum/Athene pull request #26
Opened 2020-07-13 19:48 UTC by CanArisan

Changes to the data that is exported in ClusteringResource.py. In addition to the Clusters, following will also be exported:
- Distance matrix for the distances between all text blocks
- Cluster tree representing the hierarchy of clusters

2020-08-24 20:26 UTC, bigultekin approved these changes

2020-09-01 15:36 UTC, linusmichel requested changes
Looks good, just a few small things (see inline comments).

2020-09-01 15:36 UTC, linusmichel commented on clustering/src/ClusteringResource.py
> +            })
Please add a comment on what these lines do

2020-09-01 15:36 UTC, linusmichel commented on docker-compose.yml
> +    command: gunicorn -b 0.0.0.0:8000 --reload src.app
I would adjust this in the Dockerfile instead of overriding the command in the docker-compose.

2020-09-01 15:36 UTC, linusmichel commented on docker-compose.yml
> +      - ./clustering/src:/usr/src/app/src
This should not be needed when the container is built.

2020-09-01 18:26 UTC, CanArisan commented
I updated the branch according to your feedback @linusmichel

2020-09-02 13:08 UTC, jpbernius approved these changes

2020-09-02 13:08 UTC, merged